### ISSUE TITLE
Mocha / node example doesn't seem to work (possibly for me?)

### ISSUE THREAD

**Issue by JohnMcLear** [anywhichway/benchtest#3]
```
beforeEach(benchtest.test);
afterEach(function () { benchtest.test(this.currentTest); });
after(function (){
  benchtest.report();
});
```  
```
     Uncaught ReferenceError: document is not defined (and Mocha's done() called multiple times)
      at Function.benchtest.test (node_modules/benchtest/index.js:130:21)
      at Context.<anonymous> (/home/pi/develop/tests/backend/specs/api/api.js:30:37)
      at processImmediate (node:internal/timers:463:21)
```

I also tried
```
const benchtest = require("benchtest");
afterEach(function () { benchtest.test(this.currentTest); });
after(() => benchtest.run({log:"md"}));
```
and get

```

  1) "after each" hook in "{root}":
     Uncaught ReferenceError: document is not defined (and Mocha's done() called multiple times)
      at Function.benchtest.test (node_modules/benchtest/index.js:130:21)
      at Context.<anonymous> (/home/pi/develop/tests/backend/specs/api/api.js:27:35)
      at processImmediate (node:internal/timers:463:21)

  2) "after all" hook in "{root}":
     TypeError: benchtest.run is not a function
      at Context.<anonymous> (/home/pi/develop/tests/backend/specs/api/api.js:28:23)
      at processImmediate (node:internal/timers:463:21)
```

😢

**Comment by anywhichway** [comment]
looking into this
